import os
import logging
import requests

class EmailService:
    def __init__(self):
        self.resend_api_key = os.environ.get("RESEND_API_KEY", "")
        self.api_url = "https://api.resend.com/emails"

    def send_digest_email(self, user_email, summaries_data):
        """
        Send HTML email digest with video summaries
        summaries_data: list of dicts with video info and summaries
        """
        if not self.resend_api_key:
            logging.error("Resend API key not provided")
            return False

        try:
            html_content = self._generate_email_html(summaries_data)
            
            payload = {
                "from": "TL;DW <noreply@resend.dev>",
                "to": [user_email],
                "subject": "Your TL;DW Video Digest",
                "html": html_content
            }

            headers = {
                "Authorization": f"Bearer {self.resend_api_key}",
                "Content-Type": "application/json"
            }

            response = requests.post(self.api_url, json=payload, headers=headers)
            
            if response.status_code == 200:
                logging.info(f"Email sent successfully to {user_email}")
                return True
            else:
                logging.error(f"Failed to send email: {response.status_code} - {response.text}")
                return False

        except Exception as e:
            logging.error(f"Error sending email: {e}")
            return False

    def _generate_email_html(self, summaries_data):
        """Generate HTML content for the email digest"""
        
        # Build video cards HTML
        video_cards = []
        for data in summaries_data:
            title = self._escape_html(data['title'])
            channel_title = self._escape_html(data.get('channel_title', ''))
            summary = data['summary']
            video_url = f"https://www.youtube.com/watch?v={data['video_id']}"
            thumbnail = data.get('thumbnail', '')
            
            card_html = f"""
            <div style="background: white; margin-bottom: 30px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); overflow: hidden;">
                <div style="padding: 20px; border-bottom: 1px solid #eee;">
                    <img src="{thumbnail}" alt="Video thumbnail" style="width: 100px; height: 75px; object-fit: cover; border-radius: 4px; float: left; margin-right: 15px;">
                    <div style="font-size: 1.4em; font-weight: bold; margin-bottom: 10px;">
                        <a href="{video_url}" target="_blank" style="color: #333; text-decoration: none;">{title}</a>
                    </div>
                    <div style="color: #666; font-size: 0.9em;">{channel_title}</div>
                    <div style="clear: both;"></div>
                </div>
                <div style="padding: 20px;">
                    {summary}
                </div>
            </div>
            """
            video_cards.append(card_html)
        
        # Combine all video cards
        all_videos_html = "".join(video_cards)
        
        # Complete email HTML
        html_content = f"""
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>TL;DW Video Digest</title>
        </head>
        <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; background-color: #f9f9f9;">
            <div style="text-align: center; margin-bottom: 30px; padding: 20px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; border-radius: 8px;">
                <h1>TL;DW</h1>
                <p>Your Video Digest</p>
            </div>
            
            {all_videos_html}
            
            <div style="text-align: center; margin-top: 40px; padding: 20px; color: #666; font-size: 0.9em;">
                <p>Generated by TL;DW - Making videos digestible, one summary at a time.</p>
            </div>
        </body>
        </html>
        """
        
        return html_content
    
    def _escape_html(self, text):
        """Escape HTML special characters"""
        if not text:
            return ""
        return (text.replace('&', '&amp;')
                   .replace('<', '&lt;')
                   .replace('>', '&gt;')
                   .replace('"', '&quot;')
                   .replace("'", '&#x27;'))
